### DISCUSSION TITLE
mineru2.5.4：转换效率慢&&显存累加不自动释放

### DISCUSSION THREAD

**Discussion by lixuesen163** [magicpdf/Magic-PDF#3759] [Q&A]
### 问题描述
是这样的，我在fastapi中调用了mineru，转换了一篇24页的PDF（其中有表格的是7页，其余页是纯文字），目前发现两个问题：
      1：查看日志，发现解析时间长达15~16分钟才解析完成

                ==============================================
                    2025-10-17 02:14:04.869 | INFO     | mineru.backend.vlm.vlm_analyze:get_model:81 - gpu_memory: 16 GB, batch_size: 8
                    2025-10-17 02:14:04.870 | INFO     | mineru.backend.vlm.vlm_analyze:get_model:128 - get transformers predictor cost: 3.96s
                    Downloading Model ： models/modelscope/models/OpenDataLab/MinerU2.5- 2509-1.2B
                    Predict: 100%|██████████| 24/24 [03:34<00:00,  8.94s/it]
                    Predict: 100%|██████████| 265/265 [14:30<00:00,  3.29s/it]
                    2025-10-17 02:32:13.653 | INFO     | src.routers.pdf_to_markdown.pdf_to_markdown_impl:do_parse:257 - local output dir
                ================================================================
    
               其中解析页和块分别花费3:34和14:30

      2：每次解析完成后，不能自动释放显存，第二次调用时，显存占用会累加，16G的显存第三次就溢出
                  
                ============================================================
                 **   PID USER DEV    TYPE  GPU        GPU MEM    CPU  HOST MEM Command                                         
                223681 root   0 Compute   0%   9184MiB  56%     0%   2211MiB /usr/local/bin/python -c from multiprocessing.sp
                223682 root   0 Compute   0%   6294MiB  38%     0%   2066MiB /usr/local/bin/python -c from multiprocessing.sp
                223680 root   0 Compute   0%    460MiB   3%     1%   1295MiB /usr/local/bin/python -c from multiprocessing.sp**
               ===============================================================
               进程不自动释放，第三次报错：“torch.OutOfMemoryError: CUDA out of memory. ”
               
               
我是将fastapi打包成镜像在docker中启动的，调用方式是"vlm-transformers",内存是31G空余，GPU是4060 Ti，情况如下：
Fri Oct 17 03:34:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     Off |   00000000:01:00.0 Off |                  N/A |
|  0%   40C    P8              9W /  165W |   15958MiB /  16380MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    223680      C   /usr/local/bin/python                         460MiB |
|    0   N/A  N/A    223681      C   /usr/local/bin/python                        9184MiB |
|    0   N/A  N/A    223682      C   /usr/local/bin/python                        6294MiB |
+-----------------------------------------------------------------------------------------+

按理来说，转换效率不应该这么慢呢~

**Comment by dosubot** [comment]
Hi @lixuesen163! I'm [Dosu](https://go.dosu.dev/dosubot) and I’m helping the MinerU team.


你的问题在社区中也有类似反馈，尤其是在 Docker 环境下，GPU 显存不释放和转换速度慢是已知问题。慢速主要和复杂文档（如表格页）、模型推理流程有关，显存累加则通常是模型或 tensor 没有及时释放，FastAPI 持续调用时会导致显存溢出。[相关讨论](https://github.com/opendatalab/MinerU/issues/2391#issuecomment-2834706226)

目前代码层面没有看到系统性地在每次推理后主动释放显存，比如 `torch.cuda.empty_cache()`、`del model`、`gc.collect()` 等清理操作没有在主流程中反复使用。如果模型对象或推理结果在 FastAPI 应用或全局变量中持久化，也会导致显存无法释放。

**建议尝试：**
1. 在每次推理结束后，手动执行 `torch.cuda.empty_cache()`，并删除模型对象（`del model`），再调用 `gc.collect()`，确保 Python 对象和显存都被清理。
2. 如果是多进程或多线程调用，建议每次任务结束后主动关闭进程，或用独立 worker 进程处理推理，避免主进程显存累积。
3. Docker 部署时，适当提升容器内存和显存限制，避免资源不足导致崩溃。[有用户反馈提升 Docker 内存后问题缓解](https://github.com/opendatalab/MinerU/issues/2391#issuecomment-2834706226)
4. 优化 batch_size，复杂表格页建议分批处理，减少单次显存压力。

如果你能在 FastAPI 的每次请求后加上上述清理逻辑，通常能显著改善显存累积问题。转换速度慢则和模型结构、表格页复杂度有关，目前社区也有类似反馈，暂时没有特别有效的加速方案，建议关注后续版本优化。



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=reply-with-mention&utm_term=opendatalab%2FMinerU).*

---

Docs are dead. Just use [Dosu](https://dosu.dev?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-tagline&utm_term=opendatalab%2FMinerU).

[![Leave Feedback](https://img.shields.io/badge/Leave%20Feedback-555555?style=flat)](https://app.dosu.dev/response-feedback?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-feedback&utm_term=opendatalab%2FMinerU&message_id=d0847371-181f-4513-936f-746c7f47a8d1) [![Ask Dosu about MinerU](https://img.shields.io/badge/Ask%20Dosu%20about%20MinerU-2f7b3f?style=flat&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iODYiIGhlaWdodD0iODkiIHZpZXdCb3g9IjAgMCA4NiA4OSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4yOTIzNiAxMi43OTI4TDE3Ljc1OTMgNi42ODE4OFY3Mi41NjY3TDUuMjkyMzYgODQuMDYxOFYxMi43OTI4WiIgZmlsbD0iI0I0QkI5MSIvPjxwYXRoIGQ9Ik0xOC4yNTc1IDczLjExOTZMNTkuMTMyOSA3Mi43NDhMNTEuNzAxMSA4Mi40MDk1TDI5LjAzMzggODYuMjkxTDYuMjM5NjIgODUuMTU1NEwxOC4yNTc1IDczLjExOTZaIiBmaWxsPSIjNzc4NTYxIi8%2BPHBhdGggZD0iTTE3LjQ5MTYgMy43MzYzM0wzLjU4NTU3IDEyLjcwOTlWODMuNTc5MkMzLjU4NTU3IDg0Ljc1NDIgNC45ODU2MyA4NS4zNjUyIDUuODQ3MDUgODQuNTY2TDE5LjYyOTYgNzEuNzgwMSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjQyODQ0IiBzdHJva2UtbGluZWNhcD0icm91bmQiLz48bWFzayBpZD0iZG9zdS1kLWN1dG91dCIgZmlsbD0id2hpdGUiPjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNNDAuNzA0IDAuNTE4MDY2SDE3LjA0MzlWNzYuMjIyMUg0MC43MDRINDIuNTgwNUg0Ny44MDEzQzY4LjcwNjQgNzYuMjIyMSA4NS42NTMzIDU5LjI3NTIgODUuNjUzMyAzOC4zNzAxQzg1LjY1MzMgMTcuNDY1IDY4LjcwNjMgMC41MTgwNjYgNDcuODAxMyAwLjUxODA2Nkg0Mi41ODA1SDQwLjcwNFoiLz48L21hc2s%2BPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00MC43MDQgMC41MTgwNjZIMTcuMDQzOVY3Ni4yMjIxSDQwLjcwNEg0Mi41ODA1SDQ3LjgwMTNDNjguNzA2NCA3Ni4yMjIxIDg1LjY1MzMgNTkuMjc1MiA4NS42NTMzIDM4LjM3MDFDODUuNjUzMyAxNy40NjUgNjguNzA2MyAwLjUxODA2NiA0Ny44MDEzIDAuNTE4MDY2SDQyLjU4MDVINDAuNzA0WiIgZmlsbD0iI0YzRjZGMSIvPjxwYXRoIGQ9Ik0xNy4wNDM5IDAuNTE4MDY2Vi02LjU3OTE5SDkuOTQ2NjlWMC41MTgwNjZIMTcuMDQzOVpNMTcuMDQzOSA3Ni4yMjIxSDkuOTQ2NjlWODMuMzE5NEgxNy4wNDM5Vjc2LjIyMjFaTTE3LjA0MzkgNy42MTUzMkg0MC43MDRWLTYuNTc5MTlIMTcuMDQzOVY3LjYxNTMyWk0yNC4xNDEyIDc2LjIyMjFWMC41MTgwNjZIOS45NDY2OVY3Ni4yMjIxSDI0LjE0MTJaTTQwLjcwNCA2OS4xMjQ5SDE3LjA0MzlWODMuMzE5NEg0MC43MDRWNjkuMTI0OVpNNDIuNTgwNSA2OS4xMjQ5SDQwLjcwNFY4My4zMTk0SDQyLjU4MDVWNjkuMTI0OVpNNDcuODAxMyA2OS4xMjQ5SDQyLjU4MDVWODMuMzE5NEg0Ny44MDEzVjY5LjEyNDlaTTc4LjU1NiAzOC4zNzAxQzc4LjU1NiA1NS4zNTU1IDY0Ljc4NjcgNjkuMTI0OSA0Ny44MDEzIDY5LjEyNDlWODMuMzE5NEM3Mi42MjYxIDgzLjMxOTQgOTIuNzUwNSA2My4xOTQ5IDkyLjc1MDUgMzguMzcwMUg3OC41NTZaTTQ3LjgwMTMgNy42MTUzMkM2NC43ODY2IDcuNjE1MzIgNzguNTU2IDIxLjM4NDcgNzguNTU2IDM4LjM3MDFIOTIuNzUwNUM5Mi43NTA1IDEzLjU0NTMgNzIuNjI2IC02LjU3OTE5IDQ3LjgwMTMgLTYuNTc5MTlWNy42MTUzMlpNNDIuNTgwNSA3LjYxNTMySDQ3LjgwMTNWLTYuNTc5MTlINDIuNTgwNVY3LjYxNTMyWk00MC43MDQgNy42MTUzMkg0Mi41ODA1Vi02LjU3OTE5SDQwLjcwNFY3LjYxNTMyWiIgZmlsbD0iYmxhY2siIG1hc2s9InVybCgjZG9zdS1kLWN1dG91dCkiLz48cGF0aCBkPSJNNjguOTIxNSAzNi4wMTM1QzY4LjkyMTUgMzYuMDEzNSA2NS43MzY5IDQ5LjQ3MzggNTEuNDIzMSA0OS40NzM4QzM3LjEwOTMgNDkuNDczOCAzMi41Nzg3IDM3LjM1OTYgMzIuNTc4NyAzNi4wMTM1IiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjcuNjkxNjEiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPjxwYXRoIGQ9Ik0wLjM0ODYzMyA4NS40OTQ2QzAuMzQ4NjMzIDg1LjQ5NDYgMjkuNDg1NiA4NS44MzA5IDM0LjgwOSA4NS42OThDNDQuODMzNyA4NS40NDc3IDUxLjI4NzIgODQuNDAyIDU3LjUyNjkgNzguOTcyNEM2Mi44MTI5IDc0LjM3MjcgNzUuMTM0MiA1OS42ODM2IDc1LjEzNDIgNTkuNjgzNiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjE2NDgyIi8%2BPC9zdmc%2B)](https://github.dosu.com/opendatalab/MinerU?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-ask-repo&utm_term=opendatalab%2FMinerU) [![Share Dosu with your team](https://img.shields.io/badge/Share%20Dosu%20with%20your%20team-1f6feb?style=flat)](https://app.dosu.dev/signup?referrer=openSource&source=github-footer&utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-share-team&utm_term=opendatalab%2FMinerU)

**Comment by myhloli** [comment]
backend换成vlm-vllm-async-engine试试

**Reply by lixuesen163** [reply]
2025-10-17 04:45:22,642 - INFO - 192.168.10.151:50127 - "POST /python_assistant/pdf_to_markdown HTTP/1.1" 200
    └ <mineru_vl_utils.mineru_client.MinerUClient object at 0x7f9c753c01f0>
  File "/usr/local/lib/python3.10/site-packages/mineru_vl_utils/vlm_client/base_client.py", line 214, in new_vlm_client
    return VllmAsyncEngineVlmClient(
           └ <class 'mineru_vl_utils.vlm_client.vllm_async_engine_client.VllmAsyncEngineVlmClient'>
  File "/usr/local/lib/python3.10/site-packages/mineru_vl_utils/vlm_client/vllm_async_engine_client.py", line 58, in __init__
    self.tokenizer = vllm_async_llm.tokenizer.get_lora_tokenizer()
    │                │              └ CachedQwen2TokenizerFast(name_or_path='models/modelscope/models/OpenDataLab/MinerU2___5-2509-1___2B', vocab_size=151643, mode...
    │                └ <vllm.v1.engine.async_llm.AsyncLLM object at 0x7f9c74307a60>
    └ <mineru_vl_utils.vlm_client.vllm_async_engine_client.VllmAsyncEngineVlmClient object at 0x7f9c5e299b70>
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1127, in __getattr__
    raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")

AttributeError: CachedQwen2TokenizerFast has no attribute get_lora_tokenizer

看报错貌似是源码中mineru_vl_utils/vlm_client/vllm_async_engine_client.py调用接口的兼容性问题，我的mineru_vl_utils版本是0.1.13，是最新的

**Reply by myhloli** [reply]
看下transformers版本呢

**Reply by lixuesen163** [reply]
(base) kv@ubuntu:~$ docker exec -it pdf_to_md bash
root@34b0b7a5d278:/opt# pip show transformers
Name: transformers
Version: 4.57.0

是4.57.0，需要更新吗？

**Reply by myhloli** [reply]
你可以先试着降到4.56.1

**Reply by lixuesen163** [reply]
没有区别，还是那个错误，你们可以正常调用吗？
<img width="1194" height="698" alt="image" src="https://github.com/user-attachments/assets/499dc691-249d-4358-a65d-f6d9893175bc" />
<img width="1196" height="525" alt="image" src="https://github.com/user-attachments/assets/99c0e09e-65dd-448f-9258-5256d4ab2c51" />

**Reply by lixuesen163** [reply]
显存累加的问题找到了，应该是因为我的项目用的是fastapi，启动方式是多进程，控制了一个进程，但其他的没有，导致第二次第三次请求的时候，显存使用会累加直到溢出
<img width="471" height="222" alt="image" src="https://github.com/user-attachments/assets/096b5a4f-c7ee-49b4-b21e-6ac6b308b046" />

换成单进程启动之后：
<img width="803" height="620" alt="企业微信截图_17609239089416" src="https://github.com/user-attachments/assets/bf91e868-f867-43b9-97cd-d54903401186" />

但是速度问题确实还是感觉慢，大模型说要用vllm，我再调研一下

**Reply by myhloli** [reply]
> 2025-10-17 04:45:22,642 - INFO - 192.168.10.151:50127 - "POST /python_assistant/pdf_to_markdown HTTP/1.1" 200
> 
>     └ <mineru_vl_utils.mineru_client.MinerUClient object at 0x7f9c753c01f0>
> 
>   File "/usr/local/lib/python3.10/site-packages/mineru_vl_utils/vlm_client/base_client.py", line 214, in new_vlm_client
> 
>     return VllmAsyncEngineVlmClient(
> 
>            └ <class 'mineru_vl_utils.vlm_client.vllm_async_engine_client.VllmAsyncEngineVlmClient'>
> 
>   File "/usr/local/lib/python3.10/site-packages/mineru_vl_utils/vlm_client/vllm_async_engine_client.py", line 58, in __init__
> 
>     self.tokenizer = vllm_async_llm.tokenizer.get_lora_tokenizer()
> 
>     │                │              └ CachedQwen2TokenizerFast(name_or_path='models/modelscope/models/OpenDataLab/MinerU2___5-2509-1___2B', vocab_size=151643, mode...
> 
>     │                └ <vllm.v1.engine.async_llm.AsyncLLM object at 0x7f9c74307a60>
> 
>     └ <mineru_vl_utils.vlm_client.vllm_async_engine_client.VllmAsyncEngineVlmClient object at 0x7f9c5e299b70>
> 
>   File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1127, in __getattr__
> 
>     raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
> 
> 
> 
> AttributeError: CachedQwen2TokenizerFast has no attribute get_lora_tokenizer
> 
> 
> 
> 看报错貌似是源码中mineru_vl_utils/vlm_client/vllm_async_engine_client.py调用接口的兼容性问题，我的mineru_vl_utils版本是0.1.13，是最新的

目前看来是和vllm0.11.1不兼容，需要安装0.10.1.1或0.10.2版本

**Reply by myhloli** [reply]
目前mineru_vl_utils也已更新支持vllm 0.11.x，可以通过更新mineru_vl_utils的方式支持：
pip install "mineru-vl-utils==0.1.14"

**Reply by lixuesen163** [reply]
嗯嗯，在解决“(EngineCore_DP0 pid=1053000) ModuleNotFoundError: No module named 'flash_attn.flash_attn_interface'
2025-10-20 06:01:21.774 | ERROR    | src.routers.pdf_to_markdown.pdf_to_markdown_impl:wrapper:79 - Engine core initialization failed. See root cause above. Failed core proc(s): {}”的问题了

就是“pip install flash-attn --no-build-isolation”的过程有点慢

**Reply by lixuesen163** [reply]
非常感谢！fash-attn安装很慢，但是最后成功了，调用vlm-vllm-async-engine试了一下，解析1篇24页的pdf(含4,5页表格)，大概只需要2分钟，但是第二次调用的时候，会报vllm显存崩溃的问题，官方机器人给的建议是将vllm单独起一个服务更稳妥，我后续会试一下这种方式
